# Generated by Django 4.2.2 on 2023-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='hashed_password',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
